CREATE TABLE REFINED_DATA_DB.MVIEW_WEEKLY_SALES AS 
SELECT 
POS_SITE_ID,
SKU_ID,
DATE_TRUNC('WEEK',DT) AS FSCLWK_ID,
PRICE_SUBSTATE_ID,
TYPE,
SUM(SALES_UNITS) AS TOTAL_SALES_UNITS,
SUM(SALES_DOLLARS) AS TOTAL_SALES_DOLLARS,
SUM(DISCOUNT_DOLLARS) AS TOTAL_DISOCUNT_DOLLARS
FROM ASSESSMENT_STAGING_DATA_DB.FACT_TRANSACTIONS 
GROUP BY POS_SITE_ID,SKU_ID,FSCLWK_ID,PRICE_SUBSTATE_ID,TYPE;