CREATE DATABASE IF NOT EXISTS ASSESSMENT_STAGING_DATA_DB;

-- LEVEL 1: LOCATION TABLE

CREATE TABLE ASSESSMENT_STAGING_DATA_DB.LOCATION(
LOC INT PRIMARY KEY,
LOC_LABEL STRING
);

INSERT INTO ASSESSMENT_STAGING_DATA_DB.LOCATION
SELECT LOC,LOC_LABEL FROM RAW_DATA_DB.INVLOC;

-- LEVEL 2: LOCATION TYPE TABLE

CREATE TABLE ASSESSMENT_STAGING_DATA_DB.LOCATION_TYPE(
LOCTYPE INT PRIMARY KEY,
LOCTYPE_LABEL STRING
);

INSERT INTO ASSESSMNET_STAGING_DATA_DB.LOCATION_TYPE
SELECT DISTINCT LOCTYPE,LOCTYPE_LABEL FROM RAW_DATA_DB.INVLOC;


CREATE TABLE ASSESSMENT_STAGING_DATA_DB.FACT_TRANSACTIONS AS 
SELECT T.ORDER_ID,T.LINE_ID,T.TYPE,T.DT,T.POS_SITE_ID,T.SKU_ID,T.FSCLDT_ID,T.PRICE_SUBSTATE_ID,
T.SALES_UNITS,T.SALES_DOLLARS,T.DISCOUNT_DOLLARS,T.ORIGINAL_ORDER_ID,T.ORIGINAL_LINE_ID
FROM RAW_DATA_DB.TRANSACTIONS T
JOIN ASSESSMENT_STAGING_DATA_DB.LOCATION L ON T.POS_SITE_ID=L.LOC;